[server]
headless = true
address = "0.0.0.0"
port = 5000

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00ff41"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"
textColor = "#00ff41"

[ui]
hideTopBar = true
